
SET FOREIGN_KEY_CHECKS=0;

TRUNCATE TABLE item;
TRUNCATE TABLE description;
TRUNCATE TABLE feed;
TRUNCATE TABLE result;
TRUNCATE TABLE analysis_result;

ALTER TABLE item ALTER COLUMN id RESTART WITH 1;
ALTER TABLE description ALTER COLUMN id RESTART WITH 1;
ALTER TABLE feed ALTER COLUMN id RESTART WITH 1;
ALTER TABLE result ALTER COLUMN id RESTART WITH 1;

SET FOREIGN_KEY_CHECKS=1;